version: '3.7'

services:
  db:
    image: mysql:5.7
    restart: always
    container_name: jpashop
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: "jpashop"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      TZ: Asia/Seoul
    volumes:
      - ./volumes/mysql:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci