
spring:
  profiles:
    active: local

  datasource:
    url: jdbc:mysql://localhost:3306/jpashop?useSSL=false
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging.level:
  org.hibernate.type: trace

decorator:
  datasource:
    p6spy:
      enable-logging: true